[package]
name = "pds"
version = "0.1.0"
edition = "2024"

[dependencies]
bc_exch_api_funcs = {path="dep/bc_exch_api_funcs"}

serde ={ version = "1.0", features = ["derive"]}
serde_json = "1.0"
rustc-hash = "1.1"
tokio = { version = "1", features = ["full"] }
