[package]
name = "bc_utils_core"
version = "0.1.1"
edition = "2024"

[dependencies]
bc_utils_lg ={ path = "../bc_utils_lg"}

hmac = "0.12"
sha2 = "0.10"
hex = "0.4"
reqwest = { version = "0.11.27", features = ["json"] }